# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: teeks99/boost-cpp-docker:gcc-9

steps:
- script: |
    wget https://raw.githubusercontent.com/boostorg/regression/develop/testing/src/run.py
    python run.py --runner=regression-gcc --toolset=gcc-9~c++2a --tag=master
  displayName: 'Run Regression Tests'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
